### ISSUE TITLE
Use godzilla or otto instead of quickjs to not require cgo

### ISSUE THREAD

**Issue by jasikpark** [graemephi/goldmark-qjs-katex#4]
The gohugio project has a requirement that it does not depend on `cgo` so therefore this can't be used by them.

> Perhaps use [godzilla](https://github.com/jingweno/godzilla) or [otto](https://github.com/robertkrimen/otto)? It seems otto supports `js` sans CGO. And I *think* godzilla does as well. 
https://github.com/graemephi/goldmark-qjs-katex/issues/2#issuecomment-589179945

I also might be confused because the pandoc element might be the cause of the use of cgo, isn't it.

**Comment by graemephi** [comment]
Pandoc generates the test; it's only required for development. cgo is needed to call out to quickjs, which is something godzilla or otto could replace, yes.

Godzilla looks pretty underbaked. Otto would involve embedding the KaTeX source anyway which feels like passing the buck to me. It also evaluates the AST directly, and this package is slow enough as it is.

Anyway, quickjs is in the package name.
