### ISSUE TITLE
Request: add parser context if any katex nodes exists

### ISSUE THREAD

**Issue by jschaf** [graemephi/goldmark-qjs-katex#7]
First off, loving the library. It's really nice not to have a dependency on Node.

When I run goldmark, I eventually compile the HTML into a go template. I'd like to avoid adding Katex CSS if no katex nodes exist in the document.  What do you think about a public method that reports the number of KaTeX nodes?

```
func reportKatexNodes(pc parser.Context) int {}
```

Alternatively: 
- You could further generalize `reportKatexNodex` to return a list of all katex nodes instead.
- Make the `node` struct and kind public so clients can traverse and find katex nodes themselves.

**Comment by graemephi** [comment]
Thanks!

Getting a quick count with `ReportKatexNodes` looks convenient and being able to properly traverse the AST and interact with KaTeX nodes as normal nodes definitely seems like something you'd want to be able to do.  So, I've done both of those and tagged the release `v0.3.0`.

**Comment by jschaf** [comment]
Awesome! Thanks a bunch.
